# Site Settings
#=include site.yml

# Social Media Settings
# Remove the item if you don't need it
#=include social.yml

# Posts Settings
#=include posts.yml

# Advanced Settings
#=include advanced.yml

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: ","
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.2

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 1.0
start-delay: 100
delete-delay: 5000
dynamic-text-element-id: dynamic-description
lines:
  - text: "Where’s your will to be weird?"
  - text: "Only two things are infinite: The universe and human stupidity. But I am not sure about the former! - Albert Einstein"
  - text: "Think of how stupid an average person is, and realize half of them are stupider than that!"
  - text: "There are no ghosts in the real world... save those we make for ourselves - Sherlock"
  - text: "Human consciousness was a tragic misstep in evolution. Nature created an aspect of nature separate from itself... We are creatures that should not exist by natural law! - True Detective"
  - text: "SELF CONTROL... The only way to survive in this world dominated by idiots"
  - text: "Just 'cause you got the monkey off your back	doesn't mean the circus has left the town"
  - text: "We used to look up at the sky and wonder at our place in the stars, now we just look down and worry about our place in the dirt - Interstellar"
  - text: "Love is the one thing that we're capable of perceiving that transcends time and space - Interstellar"
  - text: "Madness, as you know, is like gravity... All it takes is a little push! - \n Joker"
  - text: "History teaches us that no other cause has brought more death than the word of God!"
  - text: "Blind faith is an 'ironic gift' to return to the 'supposed' creator of Human Intelligence."
  - text: "Is man really a mistake of God... or God merely a mistake of man?"
  - text: "This world is full of idiots distributed strategically - so you can meet at least one per day"
  - text: "A creative adult is the child who survived"
  - text: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day whispering, 'I will try again tomorrow'"
  - text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment"
  - text: "We need to stare at the face of reality, and not bury our head in sand, shouting slogans about our past greatness (real or imagined)"
  - text: "Nature wants 5 of your 7 children dead. It wants you dead by 50. Everything better than that is brought to you by science and technology"
