# Site Settings
#=include site.yml

# Social Media Settings
# Remove the item if you don't need it
#=include social.yml

# Posts Settings
#=include posts.yml

# Advanced Settings
#=include advanced.yml

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: ","
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.2

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 0.01
start-delay: 100
delete-delay: 5000
dynamic-text-element-id: dynamic-description
lines: # You can add HTML tags in the Text
  - text: "When time never stops for us, then why do we wait for the right time?"
  - text: "Where’s your will to be weird?"
  - text: "Only two things are infinite: The universe and human stupidity. But I am not sure about the former!"
  - text: "Think of how stupid an average person is, and realize half of them are stupider than that!"
  - text: "Vision without execution is just hallucination."
  - text: "There are no ghosts in the real world... save those we make for ourselves!"
  - text: "You wear a mask for so long, you forget who you were beneath it."
  - text: "Human consciousness was a tragic misstep in evolution. Nature created an aspect of nature separate from itself... We are creatures that should not exist by natural law!"
  - text: "Once you have accepted your flaws, no one can use them against you."
  - text: "SELF CONTROL... The only way to survive in this world dominated by idiots."
  - text: "Sometimes your Heart needs more time to accept what your Mind already knows."
  - text: "Just 'cause you got the monkey off your back	doesn't mean the circus has left the town."
  - text: "The only thing standing between you and your goal is the bullshit story you keep telling yourself as to why you can't achieve it."
  - text: "What if when you die, you meet God and he says 'So, how was heaven?'"
  - text: "Why do we have brakes in a car?........ To enable us to safely drive faster!"
  - text: "Life is like an elevator: on your way up, sometimes, you have to stop and let some people off."
  - text: "Good friends are hard to find, difficult to leave, and impossible to forget."
  - text: "Do not go gentle into that good night. Old age should burn and rave at close of day. Rage, rage against the dying of the light."
  - text: "We used to look up at the sky and wonder at our place in the stars, now we just look down and worry about our place in the dirt."
  - text: "Love is the one thing that we're capable of perceiving that transcends time and space"
  - text: "Madness, as you know, is like gravity... All it takes is a little push"
  - text: "There once was a time when all people believed in God and the holy institutions ruled. This time was called the Dark Ages."
  - text: "History teaches us that no other cause has brought more death than the word of God!"
  - text: "Blind faith is an 'ironic gift' to return to the creator of Human Intelligence."
  - text: "Is man really a mistake of God... or God merely a mistake of man?"
  - text: "This world is full of idiots distributed stratigically - so you can meet at least one per day"
  - text: "The greatest discovery of all time is that a person can change his future by merely changing his attitude"
  - text: "It's only when you have courage to step off the ledge, that you'll realize you had wings all along"
  - text: "To live is the rarest thing in the world... Most people just exist"
  - text: "Culture is a plot against the expansion of human consciousness"
  - text: "A creative adult is the child who survived"
  - text: "It's okay to have your things messed up, rather than your thoughts"
  - text: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day whispering, 'I will try again tomorrow'"
  - text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment"
  - text: "The biggest advantage when you're just starting out is that you're hungrier than your competitor"
  - text: "Be careful while following the masses... More often than not the 'M' is silent"
  - text: "If you don't find a way to make money while you sleep, you will work until you die"
  - text: "Greatness is merely an illusion in our minds, a made-up destination that we obligate ourselves to pursue, our own psychological Atlantis"
  - text: "Winners don't make excuses when other side plays the game"
  - text: "A temple is an interesting place - The poor beg outside & the rich beg inside"
  - text: "We need to stare at the face of reality, and not bury our head in sand, shouting slogans about our past greatness (real or imagined)"
  - text: "Nature wants 5 of your 7 children dead. It wants you dead by 50. Everything better than that is brought to you by science and technology"